language: ruby
rvm:
  - "2.2.2"
env:
  - DB=sqlite
  - DB=postgresql
before_script:
  - psql -c 'create database imi_maps_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:schema:load
  - RAILS_ENV=test bundle exec rspec spec
