source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'bootstrap-sass', '2.1'
gem 'carrierwave'
gem 'geocoder'
gem 'gmaps4rails'
gem 'nested_form'
gem "country-select"

gem 'activeadmin', github: 'activeadmin'

gem 'thin'


gem "rmagick", "~> 2.13.1"
gem "paperclip", "~> 4.3.1"
#gem "date-input-rails"

gem 'chosen-rails'

gem 'kaminari'


gem 'chartkick', '~> 1.4.0'
gem "d3-rails"
gem "net-ldap"


gem 'devise'

#gem 'griddler'


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'jquery-rails'

# it was pulled from the core in Rails 4.x.
gem 'activeresource','~> 4.0.0'


# add these gems to help with the transition:
gem 'protected_attributes'
gem 'rails-observers'
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'jquery-ui-rails'
  gem 'sass-rails',   '5.0.3'
  gem 'coffee-rails', '~> 4.1.0'
  gem 'font-awesome-sass-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'

  #gem "therubyracer"
  #gem "less-rails"
  #gem 'twitter-bootstrap-rails'
end

group :test do
  gem 'factory_girl', '~> 4.2.0'
  gem "shoulda-matchers"
  gem "selenium-webdriver"
end

group :development, :test do
  gem 'rspec-rails', '~> 2.13.0'
  gem 'sqlite3'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry'
  gem 'capybara', '~> 2.1.0'
  gem 'rack-mini-profiler'
  gem 'launchy'

end

group :production do
  gem 'pg'

end

# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.10'


# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
#gem 'unicorn'
gem 'passenger', '~> 5.0.20'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger
# gem 'debugger'
